image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Build
          services:
            - docker
          script:
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker build -t ${IMAGE_NAME} .
            - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASS"
            - docker tag ${IMAGE_NAME} ${DOCKER_NAMESPACE}
            - docker push ${DOCKER_NAMESPACE}